apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state-store
spec:
  type: state.sqlite
  version: v1
  metadata:
    # Path to the database file (created automatically if it doesn't exist)
    - name: connectionString
      value: "file:./db/dapr-state.db"
    - name: tableName
      value: "state"
